apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  destination:
    namespace: webapp
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: helm/webapp
    repoURL: "https://github.com/ramil-brion/argocd-course-webapp.git"
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
